apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: test-devblog-chart-repo
  namespace: default
spec:
  interval: 5m
  url: https://mykhailo-sichkaruk.github.io/thesis-deploy/
