apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: stage-devblog
  namespace: flux-system
spec:
  interval: 20s
  path: "./config/clusters/stage-devblog"
  prune: true
  sourceRef:
    kind: GitRepository
    name: stage-devblog
  validation: client
