apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: lint-report
    files:
      - lint.json=reports/lint.json
